name: iryojoho_master
description: "医療情報技師資格取得のための学習アプリ"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状態管理とデータ
  flutter_bloc: ^8.1.4
  supabase_flutter: ^1.10.25
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2
  path: ^1.9.0

  # UI components
  flex_color_scheme: ^7.3.1
  adaptive_navigation: ^0.0.9
  fl_chart: ^0.66.2
  percent_indicator: ^4.2.3
  flutter_markdown: ^0.6.21
  table_calendar: ^3.0.9
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.7.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
